routes/web.php
<?php

use App\Http\Controllers\ExportController;
use Illuminate\Support\Facades\Route;


use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\LogoutController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SLogDosenController;
use App\Http\Controllers\LogDosenController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('/')->group(function () {
    Route::get('/', function () {
        return view('landing');
    });
    Route::resource('/kuliah', \App\Http\Controllers\LogPerkuliahanController::class);
    Route::get('/kuliah/export/excel', [\App\Http\Controllers\LogPerkuliahanController::class, 'export_excel']);
    Route::resource('/Lkegiatan', \App\Http\Controllers\LogKegiatanController::class);
    Route::post('/Lkegiatan/storePIC', [\App\Http\Controllers\LogKegiatanController::class, 'storePIC'])->name('Lkegiatan.storePIC');
});


Route::prefix('superadmin')->middleware('checkRole:superadmin')->group(function () {
    Route::get('/dashboard', [\App\Http\Controllers\SLogDosenController::class, 'dashboard'])->name('superadmin.dashboard');
    Route::get('/kuliah/export/excel', [\App\Http\Controllers\SLogDosenController::class, 'export_excel'])->name('kuliah.export.excel');
    Route::get('/kuliah/export/excelDosenMingguan', [\App\Http\Controllers\SLogDosenController::class, 'excelDosenMingguan'])->name('kuliah.export.excelDosenMingguan');
    // Route::get('/kuliah/export/excelKuliahMingguan', [\App\Http\Controllers\SLogDosenController::class, 'excelKuliahMingguan'])->name('kuliah.export.excelKuliahMingguan');
    // Route::get('/kuliah/export/excelKuliahBulanan', [\App\Http\Controllers\SLogDosenController::class, 'excelKuliahBulanan'])->name('kuliah.export.excelKuliahBulanan');
    Route::get('/kuliah/export/excelKuliahMingguan', [ExportController::class, 'exportExcel'])->name('kuliah.export.excelKuliahMingguan');
    Route::get('/kuliah/export/excelKuliahBulanan', [ExportController::class, 'exportExcelKuliahBulan'])->name('kuliah.export.excelKuliahBulanan');
    Route::get('/kuliah/export/excelDosenMingguan', [ExportController::class, 'exportExcelDosenMinggu'])->name('kuliah.export.excelDosenMingguan');
    Route::get('/kuliah/export/excelDosenBulanan', [ExportController::class, 'exportExcelDosenBulan'])->name('kuliah.export.excel');
    Route::get('/kuliah/export/excelKegiatanMingguan', [ExportController::class, 'exportExcelKegiatanMinggu'])->name('kuliah.export.excelKegiatanMingguan');
    Route::get('/kuliah/export/excelKegiatanBulanan', [ExportController::class, 'exportExcelKegiatanBulan'])->name('kuliah.export.excelKegiatanBulanan');
    Route::get('/kuliah/export/excelKegiatanPICMingguan', [ExportController::class, 'exportExcelKegiatanPICMinggu'])->name('kuliah.export.excelKegiatanPICMingguan');
    Route::get('/kuliah/export/excelKegiatanPICBulanan', [ExportController::class, 'exportExcelKegiatanPICBulan'])->name('kuliah.export.excelKegiatanPICBulanan');
    Route::resource('/kegiatan', \App\Http\Controllers\LogKegiatanController::class);
    Route::resource('/matkul', \App\Http\Controllers\MatkulController::class);
    Route::get('/historyMatkul', [\App\Http\Controllers\MatkulController::class, 'historyMatkul'])->name('historyMatkul');
    Route::resource('/labpc', \App\Http\Controllers\LabController::class);
    Route::resource('/pc', \App\Http\Controllers\PcController::class);
    Route::resource('/kuliahDosen', \App\Http\Controllers\SLogDosenController::class);
    Route::delete('/kuliahDosenMhs/{id}', [SLogDosenController::class, 'destroyMhs'])->name('kuliahDosenMhs.destroyMhs');
    Route::get('/kuliah', [\App\Http\Controllers\SLogDosenController::class, 'kuliah'])->name('kuliahDosen.kuliah');
    Route::resource('/user', UserController::class);
});


Route::middleware('checkRole:dosen,ail')->group(function () {
    Route::resource('/admin', \App\Http\Controllers\LogDosenController::class);
});


Route::get('/get-matkul-list/{idLab}', [\App\Http\Controllers\LogDosenController::class, 'getMatkulList']);
Route::get('/get-matkul-info/{idLab}/{idMatkul}', [\App\Http\Controllers\LogDosenController::class, 'getMatkulInfo']);
Route::get('/get-kelas-data', [\App\Http\Controllers\LogPerkuliahanController::class, 'getKelasData']);


Route::get('/login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('/login', [LoginController::class, 'login']);
Route::post('/logout', [LoginController::class, 'logout'])->name('logout');

resources/views/superadmin/tabel/tkuliah.blade.php
<table class="table table-striped dataTable no-footer" id="table-1" role="grid" aria-describedby="table-1_info">
    <thead>
        <tr role="row">
            <th class="text-center sorting_asc" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-sort="ascending" aria-label="#: activate to sort column descending" style="width: 35.9px;">#</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">Nama
            </th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Nomor PC: activate to sort column ascending" style="width: 182.087px;">Nomor PC</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Ruang Lab: activate to sort column ascending" style="width: 182.087px;">Ruang Lab</th>
            <th class="sorting" tabindex="1" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">Nim
            </th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">
                Kelas</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">Jam
                Masuk</th>

            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">
                Monitor</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">
                Keyboard</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">
                Mouse</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">
                Jaringan</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Task Name: activate to sort column ascending" style="width: 182.087px;">Aksi
            </th>
    </thead>
    <tbody>
        @forelse ($data as $index => $logKeg)
        <tr>
            <td>{{ $index + 1 }}</td>
            <td>{{ $logKeg->nama }}</td>
            <td>{{ $logKeg->pc }}</td>
            <td>{{ $logKeg->ruang_lab }}</td>
            <td>{{ $logKeg->nim }}</td>
            <td>{{ $logKeg->nama_kelas }}</td>
            <td>{{ $logKeg->jamMasuk }}</td>
            <td>
                @if($logKeg->monitor == 'bagus')
                <span class="badge badge-success">{{ $logKeg->monitor }}</span>
                @elseif($logKeg->monitor == 'rusak')
                <span class="badge badge-danger">{{ $logKeg->monitor }}</span>
                @else
                {{ $logKeg->monitor }}
                @endif
            </td>

            <td>
                @if($logKeg->keyboard == 'bagus')
                <span class="badge badge-success">{{ $logKeg->keyboard }}</span>
                @elseif($logKeg->keyboard == 'rusak')
                <span class="badge badge-danger">{{ $logKeg->keyboard }}</span>
                @else
                {{ $logKeg->keyboard }}
                @endif
            </td>

            <td>
                @if($logKeg->mouse == 'bagus')
                <span class="badge badge-success">{{ $logKeg->mouse }}</span>
                @elseif($logKeg->mouse == 'rusak')
                <span class="badge badge-danger">{{ $logKeg->mouse }}</span>
                @else
                {{ $logKeg->mouse }}
                @endif
            </td>

            <td>
                @if($logKeg->jaringan == 'bagus')
                <span class="badge badge-success">{{ $logKeg->jaringan }}</span>
                @elseif($logKeg->jaringan == 'rusak')
                <span class="badge badge-danger">{{ $logKeg->jaringan }}</span>
                @else
                {{ $logKeg->jaringan }}
                @endif
            </td>

            <td class="text-center">
                <form onsubmit="return confirm('Apakah Anda Yakin ?');"
                    action="{{ route('kuliahDosenMhs.destroyMhs', $logKeg->id_logkul) }}" method="post">
                    <button type="button" class="btn btn-sm btn-info" data-toggle="modal"
                        data-target="#viewModal{{ $logKeg->id_logkul }}" title="Detail">
                        <i class="fa fa-eye"></i>
                    </button>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-sm btn-danger" title="Hapus">
                        <i class="fa fa-trash"></i>
                    </button>
                </form>
            </td>

        </tr>
        @empty
        <tr>
            <td colspan="10" class="text-center">
                <div class="alert alert-danger">
                    Data logbook kuliah belum Tersedia.
                </div>
            </td>
        </tr>
        @endforelse
    </tbody>
</table>

resources/views/superadmin/tabel/tlogdosen.blade.php
<table class="table table-striped dataTable no-footer" id="table-1" role="grid" aria-describedby="table-1_info">
    <thead>
        <tr role="row">
            <th class="text-center sorting_asc" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-sort="ascending" aria-label="#: activate to sort column descending" style="width: 35.9px;">#</th>
            <th class="sorting" tabindex="1" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Nama: activate to sort column ascending" style="width: 182.087px;">Nama</th>
            <th class="sorting" tabindex="1" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Nama: activate to sort column ascending" style="width: 182.087px;">Jabatan</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="ID Lab: activate to sort column ascending" style="width: 182.087px;">Lab</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Jam Masuk: activate to sort column ascending" style="width: 182.087px;">Jam Masuk</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Jam Keluar: activate to sort column ascending" style="width: 182.087px;">Matkul</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Keterangan: activate to sort column ascending" style="width: 182.087px;">Keterangan</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Jumlah Mahasiswa: activate to sort column ascending" style="width: 182.087px;">Jumlah
                Mahasiswa</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Durasi: activate to sort column ascending" style="width: 182.087px;">Durasi</th>
            <th class="sorting" tabindex="0" aria-controls="table-1" rowspan="1" colspan="1"
                aria-label="Aksi: activate to sort column ascending" style="width: 182.087px;">Aksi</th>
        </tr>
    </thead>
    <tbody>
        @forelse ($data as $index => $logKeg)
        <tr>
            <td>{{ $index + 1 }}</td>
            <td>{{ $logKeg->nama }}</td>
            <td>{{ $logKeg->jabatan }}</td>
            <td>{{ $logKeg->ruang_lab }}</td>
            <td>{{ $logKeg->jamMasuk }}</td>
            <td>{{ $logKeg->matkul }}</td>
            <td>{{ $logKeg->keterangan }}</td>
            <td>{{ $logKeg->jumlahMhs }}</td>
            <td>{{ $logKeg->durasi }} Menit</td>
            <td class="text-center">
                <button type="button" class="btn btn-sm btn-info" data-toggle="modal"
                    data-target="#viewModal{{ $logKeg->id_logkul }}">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                </button>
                <form style="display: inline-block;" onsubmit="return confirm('Apakah Anda Yakin ?');"
                    action="{{ route('kuliahDosen.destroy', $logKeg->id_logkul) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash"></i></button>
                </form>
            </td>
        </tr>
        @empty
        <tr>
            <td colspan="7" class="text-center">
                <div class="alert alert-danger">
                    Data logbook kegiatan belum tersedia.
                </div>
            </td>
        </tr>
        @endforelse
    </tbody>
</table>